/**
 * Trade Opportunity Card Component — `apps/web/src/components/TradeCard.tsx`
 *
 * Displays a single trade opportunity recommendation generated by the
 * LangGraph analysis pipeline. Used in the TradeOpportunities page's
 * filterable card grid.
 *
 * Key features:
 * - 🟢 LONG / 🔴 SHORT emoji direction indicators (AAP Rule 0.7.5)
 * - Direction-colored left border (green = LONG, red = SHORT)
 * - Monospace price grid with tabular-nums for digit alignment
 * - Market badge with flag emoji, timeframe badge, status badge
 * - Confidence percentage with color coding (green ≥80%, yellow ≥60%)
 * - Reasoning text truncated to 3 lines
 *
 * CRITICAL — Financial Precision (AAP Rule 0.7.2):
 * All price fields (`entryPrice`, `stopLoss`, `takeProfit`, `riskRewardRatio`)
 * are `string` in the `TradeOpportunity` interface. They are displayed as-is —
 * NEVER passed through `parseFloat()`, `Number()`, or `.toFixed()`.
 *
 * @module apps/web/src/components/TradeCard
 */

import clsx from 'clsx';
import { Direction, Market, Timeframe, OpportunityStatus } from '../types';
import type { TradeOpportunity } from '../types';

// ---------------------------------------------------------------------------
// Props Interface
// ---------------------------------------------------------------------------

/** Props for the {@link TradeCard} component. */
interface TradeCardProps {
  /** The trade opportunity data to display. */
  opportunity: TradeOpportunity;
  /** Optional additional CSS class name(s) for the card root element. */
  className?: string;
}

// ---------------------------------------------------------------------------
// Helper Functions
// ---------------------------------------------------------------------------

/**
 * Returns the emoji, display label, and CSS color class for a trade direction.
 *
 * Per AAP Rule 0.7.5:
 * - 🟢 for LONG recommendations
 * - 🔴 for SHORT recommendations
 */
function getDirectionDisplay(direction: Direction): {
  emoji: string;
  label: string;
  colorClass: string;
} {
  if (direction === Direction.LONG) {
    return { emoji: '🟢', label: 'LONG', colorClass: 'text-success' };
  }
  return { emoji: '🔴', label: 'SHORT', colorClass: 'text-danger' };
}

/**
 * Formats a confidence score (0.00–1.00) as a whole-number percentage string.
 *
 * `confidence` is a `number`, not a financial price — multiplication and
 * rounding are permitted here (AAP Rule 0.7.2 applies only to price strings).
 */
function formatConfidence(confidence: number): string {
  return `${(confidence * 100).toFixed(0)}%`;
}

/**
 * Returns a CSS color class based on the confidence threshold:
 * - ≥ 0.80 → green (`text-success`)
 * - ≥ 0.60 → yellow (`text-warning`)
 * - < 0.60 → default text color (empty string)
 */
function getConfidenceColorClass(confidence: number): string {
  if (confidence >= 0.8) return 'text-success';
  if (confidence >= 0.6) return 'text-warning';
  return '';
}

/**
 * Maps an {@link OpportunityStatus} enum value to a badge CSS class.
 *
 * | Status      | Badge Class     | Visual          |
 * |-------------|-----------------|-----------------|
 * | ACTIVE      | badge-success   | Green           |
 * | CLOSED      | badge-info      | Blue            |
 * | EXPIRED     | badge-warning   | Yellow          |
 * | CANCELLED   | badge-danger    | Red             |
 */
function getStatusBadgeClass(status: OpportunityStatus): string {
  const classes: Record<OpportunityStatus, string> = {
    [OpportunityStatus.ACTIVE]: 'badge-success',
    [OpportunityStatus.CLOSED]: 'badge-info',
    [OpportunityStatus.EXPIRED]: 'badge-warning',
    [OpportunityStatus.CANCELLED]: 'badge-danger',
  };
  return classes[status];
}

/**
 * Maps an {@link OpportunityStatus} enum value to a human-readable label.
 */
function getStatusLabel(status: OpportunityStatus): string {
  const labels: Record<OpportunityStatus, string> = {
    [OpportunityStatus.ACTIVE]: 'Active',
    [OpportunityStatus.CLOSED]: 'Closed',
    [OpportunityStatus.EXPIRED]: 'Expired',
    [OpportunityStatus.CANCELLED]: 'Cancelled',
  };
  return labels[status];
}

/**
 * Maps a {@link Timeframe} enum value to a human-readable display label.
 *
 * Note: The enum member `Timeframe.POSITION` displays as "Positional"
 * for user-friendly readability.
 */
function getTimeframeLabel(timeframe: Timeframe): string {
  const labels: Record<Timeframe, string> = {
    [Timeframe.INTRADAY]: 'Intraday',
    [Timeframe.SWING]: 'Swing',
    [Timeframe.POSITION]: 'Positional',
  };
  return labels[timeframe];
}

/**
 * Maps a {@link Market} enum value to a display label with a flag/icon emoji.
 *
 * | Market         | Display       |
 * |----------------|---------------|
 * | US_STOCK       | 🇺🇸 US        |
 * | INDIAN_EQUITY  | 🇮🇳 India     |
 * | CRYPTO         | ₿ Crypto      |
 * | SOCIAL         | 💬 Social     |
 */
function getMarketLabel(market: Market): string {
  const labels: Record<Market, string> = {
    [Market.US_STOCK]: '🇺🇸 US',
    [Market.INDIAN_EQUITY]: '🇮🇳 India',
    [Market.CRYPTO]: '₿ Crypto',
    [Market.SOCIAL]: '💬 Social',
  };
  return labels[market];
}

// ---------------------------------------------------------------------------
// TradeCard Component
// ---------------------------------------------------------------------------

/**
 * Renders a trade opportunity card with direction indicator, price grid,
 * meta badges, confidence score, and reasoning text.
 *
 * The card uses the `.card` base class from globals.css and adds a
 * direction-colored left border (green for LONG, red for SHORT) via
 * CSS logical property `border-inline-start`.
 *
 * @example
 * ```tsx
 * <TradeCard opportunity={tradeOpportunity} className="custom-class" />
 * ```
 */
export default function TradeCard({
  opportunity,
  className,
}: TradeCardProps): React.JSX.Element {
  const {
    symbol,
    market,
    direction,
    confidence,
    entryPrice,
    stopLoss,
    takeProfit,
    timeframe,
    reasoning,
    riskRewardRatio,
    status,
  } = opportunity;

  const dirDisplay = getDirectionDisplay(direction);
  const confidenceText = formatConfidence(confidence);
  const confidenceColor = getConfidenceColorClass(confidence);
  const statusBadge = getStatusBadgeClass(status);
  const statusLabel = getStatusLabel(status);
  const tfLabel = getTimeframeLabel(timeframe);
  const mktLabel = getMarketLabel(market);

  return (
    <article
      className={clsx('card', className)}
      style={{
        /* Dynamic direction-colored left border — uses CSS logical property.
           `direction` is a Direction enum value ('long' | 'short') which maps
           directly to CSS custom properties --color-long / --color-short. */
        borderInlineStart: `3px solid var(--color-${direction})`,
      }}
    >
      {/* ── Header: Direction + Symbol + Status ────────────────────── */}
      <div className="flex items-center gap-2 mb-3">
        <span
          className="flex-shrink-0"
          style={{ fontSize: '1.2em' }}
          role="img"
          aria-label={`${dirDisplay.label} direction`}
        >
          {dirDisplay.emoji}
        </span>
        <span className={clsx('font-semibold', dirDisplay.colorClass)}>
          {dirDisplay.label}
        </span>
        <h3 className="font-mono font-bold text-xl flex-1">{symbol}</h3>
        <span className={clsx('badge', statusBadge)}>{statusLabel}</span>
      </div>

      {/* ── Meta row: Market + Timeframe + Confidence ──────────────── */}
      <div className="flex items-center flex-wrap gap-2 mb-3">
        <span className="badge badge-neutral">{mktLabel}</span>
        <span className="badge badge-accent">{tfLabel}</span>
        <span className={clsx('ml-auto text-sm whitespace-nowrap', confidenceColor)}>
          Confidence: <strong>{confidenceText}</strong>
        </span>
      </div>

      {/* ── Price grid: Entry, Stop Loss, Take Profit, R:R ─────────
           CRITICAL (AAP Rule 0.7.2): All price values are `string`.
           Displayed as-is — NO parseFloat, Number(), or .toFixed().
           Wrapped in <code> for monospace formatting per AAP Rule 0.7.5. */}
      <div className="grid grid-cols-2 gap-3 p-3 bg-background rounded-md my-3">
        <div className="stat">
          <span className="stat-label">Entry</span>
          <code className="price">{entryPrice}</code>
        </div>
        <div className="stat">
          <span className="stat-label">Stop Loss</span>
          <code className="price text-danger">{stopLoss}</code>
        </div>
        <div className="stat">
          <span className="stat-label">Take Profit</span>
          <code className="price text-success">{takeProfit}</code>
        </div>
        <div className="stat">
          <span className="stat-label">Risk:Reward</span>
          <code className="price">{riskRewardRatio || '—'}</code>
        </div>
      </div>

      {/* ── Reasoning text (truncated to 3 lines) ──────────────────── */}
      {reasoning !== '' && (
        <div className="mt-3">
          <p className="text-secondary text-sm line-clamp-3 break-words">
            {reasoning}
          </p>
        </div>
      )}
    </article>
  );
}
