/**
 * Analysis Logs Table Schema
 *
 * Defines the `analysis_logs` PostgreSQL table using Drizzle ORM `pg-core`.
 * This table logs every LangGraph pipeline execution step for auditing,
 * cost tracking, and performance monitoring.
 *
 * Each article processed through the four-stage AI pipeline generates one
 * record per pipeline step (filter → sentiment → trade_detect → recommend).
 * Not every article reaches all four stages — the conditional short-circuiting
 * in the LangGraph pipeline means only ~25% of articles reach the expensive
 * recommendation stage (AAP Rule 0.7.3).
 *
 * Key design decisions:
 *  - Cost uses numeric(10,6) for micro-dollar LLM cost tracking
 *    (e.g., 0.000250 USD per DeepSeek filter call) — AAP Rule 0.7.2.
 *  - JSONB `result` column stores varying pipeline step outputs:
 *    filter → { isRelevant, reason }, sentiment → { score, label, reasoning },
 *    trade_detect → { hasOpportunity, symbols, direction },
 *    recommend → full TradeRecommendation object.
 *  - Composite index on (article_id, pipeline_step) for per-article
 *    pipeline step lookup (AAP Section 0.4.3).
 *
 * Consumers:
 *  - analyzer/nodes/*.ts     → Each node creates a log entry with tokens/cost
 *  - analyzer/index.ts       → Orchestrator logs overall pipeline execution
 *  - performance.routes.ts   → Queries for cost/performance dashboards
 *  - relations.ts            → Defines many-to-one relation to news_articles
 */

import {
  pgTable,
  uuid,
  text,
  integer,
  numeric,
  timestamp,
  jsonb,
  index,
} from "drizzle-orm/pg-core";

import { pipelineStepEnum } from "./enums.js";
import { newsArticles } from "./news-articles.js";

// ---------------------------------------------------------------------------
// Table Definition
// ---------------------------------------------------------------------------

/**
 * The `analysis_logs` table records every individual LangGraph pipeline step
 * execution for each news article processed through the AI analysis pipeline.
 *
 * A single article may produce 1–4 log entries depending on how far it
 * progresses through the pipeline:
 *  - Articles deemed irrelevant by the filter step produce only 1 entry.
 *  - Articles that pass all four stages produce 4 entries.
 *
 * This enables granular cost tracking (which model, how many tokens, at what
 * price), performance monitoring (wall-clock duration per step), and debugging
 * (error capture and structured result inspection).
 */
export const analysisLogs = pgTable(
  "analysis_logs",
  {
    /** Unique log entry identifier (UUID v4, auto-generated) */
    id: uuid("id").defaultRandom().primaryKey(),

    /**
     * Foreign key to the news article being analyzed.
     * Establishes a many-to-one relationship: each article can have
     * multiple log entries (one per pipeline step it passes through).
     */
    articleId: uuid("article_id")
      .notNull()
      .references(() => newsArticles.id),

    /**
     * Which LangGraph pipeline stage produced this log entry.
     * Uses the PostgreSQL enum type from enums.ts with values:
     * filter, sentiment, trade_detect, recommend.
     */
    pipelineStep: pipelineStepEnum("pipeline_step").notNull(),

    /**
     * LLM model identifier used for this pipeline step.
     * Matches the OpenRouter model string format.
     * Examples:
     *  - "deepseek/deepseek-v3.2"       (filter stage)
     *  - "anthropic/claude-3.5-haiku"    (sentiment / trade_detect stages)
     *  - "anthropic/claude-3.5-sonnet"   (recommend stage)
     */
    modelUsed: text("model_used").notNull(),

    /**
     * Number of input tokens consumed by the LLM call.
     * Nullable because token counts may not be available if the call fails
     * before completion or the provider doesn't report them.
     */
    inputTokens: integer("input_tokens"),

    /**
     * Number of output tokens generated by the LLM call.
     * Nullable for the same reasons as inputTokens.
     */
    outputTokens: integer("output_tokens"),

    /**
     * Cost in USD for this LLM call with micro-dollar precision.
     * Uses numeric(10,6) to accurately track costs like $0.000250
     * for a DeepSeek V3.2 filter call (AAP Rule 0.7.2).
     * Nullable because cost may not be calculable if token counts
     * are unavailable or the call failed.
     */
    cost: numeric("cost", { precision: 10, scale: 6 }),

    /**
     * Wall-clock time in milliseconds for the LLM call.
     * Measures the total round-trip time including network latency
     * and model inference time. Used for performance monitoring
     * and identifying slow pipeline steps.
     */
    durationMs: integer("duration_ms"),

    /**
     * Structured output from the pipeline step stored as JSONB.
     * The schema varies by pipeline step:
     *  - filter:       { isRelevant: boolean, reason: string }
     *  - sentiment:    { score: number, label: string, reasoning: string }
     *  - trade_detect: { hasOpportunity: boolean, symbols: string[], direction: string }
     *  - recommend:    Full TradeRecommendation with entry/stop/target prices
     *
     * Nullable because the result may not be available if the step failed.
     */
    result: jsonb("result"),

    /**
     * Error message if the pipeline step failed.
     * Null on successful execution. Contains the error message string
     * (not a stack trace) for failed LLM calls, parse errors, or
     * validation failures from Zod structured output parsing.
     */
    error: text("error"),

    /**
     * When this log entry was created.
     * Automatically set to the current timestamp on insert.
     * Uses timestamp with timezone for correct UTC storage.
     */
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    /**
     * Composite index for per-article pipeline step lookup (AAP Section 0.4.3).
     * Enables efficient queries like:
     *  - "Get all analysis steps for article X" (by articleId)
     *  - "Find the sentiment result for article Y" (by articleId + pipelineStep)
     *  - "How many articles reached the recommend stage?" (by pipelineStep)
     */
    index("idx_analysis_logs_article_step").on(
      table.articleId,
      table.pipelineStep,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Inferred TypeScript Types
// ---------------------------------------------------------------------------

/**
 * Type for SELECT query results — represents a complete analysis log row
 * from the database with all columns populated (including auto-generated
 * fields like id and createdAt).
 */
export type AnalysisLog = typeof analysisLogs.$inferSelect;

/**
 * Type for INSERT values — represents the data needed to create a new
 * analysis log record. Auto-generated columns (id, createdAt) and
 * nullable columns (inputTokens, outputTokens, cost, durationMs,
 * result, error) are optional.
 */
export type NewAnalysisLog = typeof analysisLogs.$inferInsert;
