/**
 * Notification Logs Table Schema
 *
 * Defines the `notification_logs` PostgreSQL table using Drizzle ORM `pg-core`.
 * This table tracks all trade alert notifications sent (or attempted) to users
 * via the Telegram bot, including delivery status, error tracking, and the
 * Telegram message ID for post-send operations (editing, deletion).
 *
 * Each record represents one notification dispatched to one user for one
 * trade opportunity. The composite index on `(opportunity_id, user_id)` enables
 * efficient duplicate-notification prevention — the notification worker checks
 * whether a log entry already exists before sending to avoid spamming users with
 * the same alert (AAP Section 0.4.3).
 *
 * Design decisions:
 *  - `status` is a plain TEXT column (not a PostgreSQL enum) because delivery
 *    statuses are operational concerns that may need quick extension (e.g.,
 *    adding "retrying", "rate_limited") without requiring a schema migration.
 *  - `telegram_message_id` is nullable because the ID is only available after
 *    a successful Telegram API sendMessage response.
 *  - `sent_at` is nullable because the timestamp is recorded only on actual
 *    successful delivery, not on initial log creation.
 *  - `error` is nullable — only populated when `status` is "failed".
 *
 * Foreign key relationships:
 *  - notification_logs.opportunity_id → trade_opportunities.id (many-to-one)
 *  - notification_logs.user_id        → user_settings.id (many-to-one)
 *
 * Consumers:
 *  - queues/workers/notifications.worker.ts → Inserts log entries after dispatch
 *  - services/notifier/index.ts             → Checks existing logs for dedup
 *  - db/schema/relations.ts                 → Defines Drizzle relations
 *  - routes/performance.routes.ts           → Queries notification stats
 *
 * @module notification-logs
 */

import {
  pgTable,
  uuid,
  text,
  integer,
  timestamp,
  index,
} from "drizzle-orm/pg-core";

import { tradeOpportunities } from "./trade-opportunities.js";
import { userSettings } from "./user-settings.js";

// ---------------------------------------------------------------------------
// Table Definition
// ---------------------------------------------------------------------------

/**
 * The `notification_logs` table — tracks Telegram trade alert delivery status.
 *
 * Lifecycle of a notification log entry:
 *  1. Created with status "pending" when the notification worker picks up
 *     a trade opportunity that matches a user's preferences.
 *  2. Transitions to "sent" when the Telegram Bot API returns a successful
 *     response with a message ID.
 *  3. Transitions to "failed" if the Telegram API call throws an error,
 *     with the error message captured in the `error` column.
 *  4. May be "skipped" if the user's preferences no longer match at send
 *     time (e.g., they deactivated notifications between queue and send).
 *
 * Status values: "pending" | "sent" | "failed" | "skipped"
 */
export const notificationLogs = pgTable(
  "notification_logs",
  {
    /** Unique notification log identifier — UUID v4 generated by PostgreSQL. */
    id: uuid("id").defaultRandom().primaryKey(),

    /**
     * Foreign key to the trade opportunity that triggered this notification.
     * Establishes a many-to-one relationship: one trade opportunity can
     * generate notifications to many subscribed users.
     * NOT NULL — every notification must be linked to a specific opportunity.
     */
    opportunityId: uuid("opportunity_id")
      .notNull()
      .references(() => tradeOpportunities.id),

    /**
     * Foreign key to the user who received (or should receive) this alert.
     * Establishes a many-to-one relationship: one user can have many
     * notification log entries across different trade opportunities.
     * NOT NULL — every notification must be targeted to a specific user.
     */
    userId: uuid("user_id")
      .notNull()
      .references(() => userSettings.id),

    /**
     * Telegram message ID returned by the Bot API after successful delivery.
     * Nullable because the ID is only available after a successful send.
     * Can be used for future features: editing sent messages, deleting
     * outdated alerts, or tracking read receipts.
     */
    telegramMessageId: integer("telegram_message_id"),

    /**
     * Delivery status of the notification.
     * Plain TEXT (not a PostgreSQL enum) for operational flexibility —
     * new statuses can be added without schema migration.
     *
     * Valid values:
     *  - "pending"  — Log entry created, awaiting Telegram send
     *  - "sent"     — Successfully delivered via Telegram Bot API
     *  - "failed"   — Telegram API call failed (see `error` column)
     *  - "skipped"  — User preferences no longer match at send time
     *
     * Default: "pending" — set when the worker first creates the entry.
     */
    status: text("status").notNull().default("pending"),

    /**
     * Error message captured when notification delivery fails.
     * Nullable — only populated when `status` is "failed".
     * Contains the stringified error from the Telegram Bot API or
     * internal processing error for debugging and retry decisions.
     */
    error: text("error"),

    /**
     * Timestamp when the notification was actually sent to Telegram.
     * Nullable because this is only recorded on successful delivery.
     * Stored with timezone for accurate cross-timezone representation.
     * Used for calculating notification latency (created_at → sent_at).
     */
    sentAt: timestamp("sent_at", { withTimezone: true }),

    /**
     * Timestamp when this notification log entry was created.
     * Stored with timezone for accurate cross-timezone representation.
     * Auto-populated by PostgreSQL via `DEFAULT NOW()`.
     * NOT NULL — every entry must have a creation timestamp.
     */
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    /**
     * Composite index on (opportunity_id, user_id) for duplicate notification
     * prevention per AAP Section 0.4.3.
     *
     * This index enables efficient lookup to answer: "Has user X already been
     * notified about opportunity Y?" — the notification worker queries this
     * before dispatching to avoid sending the same alert twice.
     *
     * Also supports queries that aggregate notifications per opportunity
     * (e.g., "how many users were notified about this trade?").
     */
    index("idx_notification_logs_opportunity_user").on(
      table.opportunityId,
      table.userId,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Inferred TypeScript Types
// ---------------------------------------------------------------------------

/**
 * TypeScript type for a `notification_logs` row returned by SELECT queries.
 * Includes all columns with their resolved TypeScript types.
 *
 * Example usage:
 * ```typescript
 * const log: NotificationLog = await db.query.notificationLogs.findFirst({
 *   where: and(
 *     eq(notificationLogs.opportunityId, opportunityId),
 *     eq(notificationLogs.userId, userId),
 *   ),
 * });
 * ```
 */
export type NotificationLog = typeof notificationLogs.$inferSelect;

/**
 * TypeScript type for INSERT operations on the `notification_logs` table.
 * Required fields: opportunityId, userId (all others have defaults or are nullable).
 *
 * Example usage:
 * ```typescript
 * const newLog: NewNotificationLog = {
 *   opportunityId: "550e8400-e29b-41d4-a716-446655440000",
 *   userId: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
 *   status: "sent",
 *   telegramMessageId: 12345,
 *   sentAt: new Date(),
 * };
 * await db.insert(notificationLogs).values(newLog);
 * ```
 */
export type NewNotificationLog = typeof notificationLogs.$inferInsert;
