/**
 * User Settings Table Schema
 *
 * Defines the `user_settings` table using Drizzle ORM's `pg-core` module.
 * Stores Telegram bot subscriber preferences for trade alert notifications.
 *
 * Each user (identified by their unique Telegram chat ID) can configure:
 *  - Which markets to receive alerts for (US stocks, Indian equities, crypto, social)
 *  - Minimum confidence threshold for trade recommendations (0.00–1.00)
 *  - Which timeframes to track (intraday, swing, position)
 *  - Whether notifications are active or paused
 *
 * Design decisions:
 *  - `telegram_chat_id` stored as TEXT to avoid integer overflow with large Telegram IDs
 *  - UNIQUE constraint on `telegram_chat_id` for fast subscriber lookup (AAP §0.4.3)
 *  - `markets` and `timeframes` as TEXT[] arrays for simplicity over junction tables
 *  - `min_confidence` as NUMERIC(3,2) for exact decimal precision (AAP Rule §0.7.2)
 *  - `is_active` enables soft-disable without losing user preferences
 *
 * Consumers:
 *  - bot/commands/start.ts       → creates new user record on /start
 *  - bot/commands/settings.ts    → reads/displays current preferences
 *  - bot/callbacks.ts            → updates preferences from inline keyboard selections
 *  - services/notifier/index.ts  → queries users to match preferences vs opportunities
 *  - queues/workers/notifications.worker.ts → reads active users for dispatch
 *  - routes/settings.routes.ts   → REST CRUD for user preferences
 *  - db/schema/relations.ts      → defines user_settings → notification_logs (one-to-many)
 *  - db/seed.ts                  → seeds a test user with onConflictDoNothing
 *
 * @module user-settings
 */

import {
  pgTable,
  uuid,
  text,
  numeric,
  boolean,
  timestamp,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// Table Definition
// ---------------------------------------------------------------------------

/**
 * The `user_settings` table — stores Telegram subscriber notification preferences.
 *
 * Columns:
 *  - id              : UUID primary key with auto-generated random value
 *  - telegramChatId  : Unique Telegram chat identifier (TEXT, NOT NULL, UNIQUE)
 *  - username        : Optional Telegram display name
 *  - markets         : TEXT[] of subscribed market segments (default: empty)
 *  - minConfidence   : NUMERIC(3,2) minimum confidence threshold (default: "0.70")
 *  - timeframes      : TEXT[] of subscribed trade timeframes (default: empty)
 *  - isActive        : Whether the user receives notifications (default: true)
 *  - createdAt       : Account creation timestamp with timezone
 *  - updatedAt       : Last preference update timestamp with timezone
 */
export const userSettings = pgTable("user_settings", {
  /** Unique user settings identifier — UUID v4 generated by PostgreSQL. */
  id: uuid("id").defaultRandom().primaryKey(),

  /**
   * Telegram chat ID for sending messages.
   * Stored as TEXT because Telegram chat IDs can be very large numbers that
   * exceed PostgreSQL integer range. The UNIQUE constraint (via `.unique()`)
   * enables fast subscriber lookup and prevents duplicate registrations.
   * Used by the seed script's `onConflictDoNothing()` for idempotent seeding.
   */
  telegramChatId: text("telegram_chat_id").notNull().unique(),

  /**
   * Telegram username — optional, for display purposes only.
   * May be null if the user hasn't set a Telegram username.
   */
  username: text("username"),

  /**
   * Array of market preferences the user wants alerts for.
   * Valid values correspond to the `market` enum: "us_stock", "indian_equity",
   * "crypto", "social". An empty array means the user hasn't selected any markets
   * (no alerts will be sent until they configure preferences via /settings).
   *
   * PostgreSQL type: TEXT[] with DEFAULT '{}'
   */
  markets: text("markets").array().notNull().default([]),

  /**
   * Minimum confidence threshold for trade alert notifications.
   * Uses NUMERIC(3,2) for exact decimal precision per AAP Rule §0.7.2.
   * Range: 0.00 to 1.00 (e.g., 0.70 means only alerts with ≥70% confidence).
   * Default is "0.70" — string to preserve decimal precision in Drizzle ORM.
   */
  minConfidence: numeric("min_confidence", { precision: 3, scale: 2 })
    .notNull()
    .default("0.70"),

  /**
   * Array of timeframe preferences for trade recommendations.
   * Valid values correspond to the `timeframe` enum: "intraday", "swing", "position".
   * An empty array means no timeframe filter (user may receive alerts for all timeframes,
   * or none until configured via /settings).
   *
   * PostgreSQL type: TEXT[] with DEFAULT '{}'
   */
  timeframes: text("timeframes").array().notNull().default([]),

  /**
   * Whether the user is actively receiving notifications.
   * Enables soft-disable: users can pause alerts without losing their preference
   * configuration. Toggled via the /settings Telegram bot command.
   * Default: true (notifications enabled on registration).
   */
  isActive: boolean("is_active").notNull().default(true),

  /**
   * Timestamp when the user registered (created their settings record).
   * Stored with timezone for accurate cross-timezone representation.
   * Auto-populated by PostgreSQL via `DEFAULT NOW()`.
   */
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),

  /**
   * Timestamp of the most recent preference update.
   * Stored with timezone for accurate cross-timezone representation.
   * Initially set to creation time; updated whenever preferences change.
   */
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

// ---------------------------------------------------------------------------
// Inferred TypeScript Types
// ---------------------------------------------------------------------------

/**
 * TypeScript type for a `user_settings` row returned by SELECT queries.
 * Includes all columns with their resolved TypeScript types.
 *
 * Example usage:
 * ```typescript
 * const user: UserSettings = await db.query.userSettings.findFirst({
 *   where: eq(userSettings.telegramChatId, chatId),
 * });
 * ```
 */
export type UserSettings = typeof userSettings.$inferSelect;

/**
 * TypeScript type for INSERT operations on the `user_settings` table.
 * Required fields: telegramChatId (all others have defaults or are nullable).
 *
 * Example usage:
 * ```typescript
 * const newUser: NewUserSettings = {
 *   telegramChatId: "123456789",
 *   username: "trader_joe",
 *   markets: ["us_stock", "crypto"],
 *   minConfidence: "0.80",
 *   timeframes: ["swing", "position"],
 * };
 * await db.insert(userSettings).values(newUser).onConflictDoNothing();
 * ```
 */
export type NewUserSettings = typeof userSettings.$inferInsert;
