/**
 * Trade Opportunity and Performance Domain Type Definitions
 *
 * Types for the Trading Intelligence Application's trade analysis and
 * recommendation system. These types map directly to the `trade_opportunities`
 * and `trade_performance` database tables and are consumed by:
 *   - `apps/api/src/services/analyzer/` (LangGraph pipeline output)
 *   - `apps/api/src/services/notifier/` (Telegram alert formatting)
 *   - `apps/api/src/routes/opportunities.routes.ts` (REST API responses)
 *   - `apps/web/src/pages/TradeOpportunities.tsx` (dashboard display)
 *
 * Design constraints (AAP Rules):
 * - No `any` type — `unknown` used for flexible fields (Rule 0.7.1)
 * - String enums with lowercase values matching PostgreSQL enum definitions
 *   in `apps/api/src/db/schema/enums.ts` (Rule 0.7.2)
 * - All price fields are `string` — representing PostgreSQL `numeric(12,4)`,
 *   never JavaScript floating-point `number` (Rule 0.7.2)
 * - Confidence uses `number` (range 0.00–1.00) — `numeric(3,2)` in database
 * - All date fields use ISO 8601 `string` for JSON serialization
 * - Compiles under TypeScript strict mode with `exactOptionalPropertyTypes`
 */

import type { Market } from './news.js';

// ---------------------------------------------------------------------------
// Direction Enum
// ---------------------------------------------------------------------------

/**
 * Trade direction indicator for a recommended position.
 *
 * String values MUST match the PostgreSQL `direction` enum values defined in
 * `apps/api/src/db/schema/enums.ts`.
 *
 * Telegram alert emoji mapping (AAP Rule 0.7.5):
 * - `LONG`  → 🟢 (buy recommendation)
 * - `SHORT` → 🔴 (sell recommendation)
 */
export enum Direction {
  LONG = 'long',
  SHORT = 'short',
}

// ---------------------------------------------------------------------------
// Timeframe Enum
// ---------------------------------------------------------------------------

/**
 * Trade timeframe classification for how long a position is expected to be held.
 *
 * String values MUST match the PostgreSQL `timeframe` enum values defined in
 * `apps/api/src/db/schema/enums.ts`.
 *
 * | Value      | Holding Period             |
 * |------------|----------------------------|
 * | `intraday` | Same-day trades            |
 * | `swing`    | Multi-day to multi-week    |
 * | `position` | Multi-week to multi-month  |
 */
export enum Timeframe {
  INTRADAY = 'intraday',
  SWING = 'swing',
  POSITION = 'position',
}

// ---------------------------------------------------------------------------
// OpportunityStatus Enum
// ---------------------------------------------------------------------------

/**
 * Lifecycle status of a trade opportunity.
 *
 * String values MUST match the PostgreSQL `status` enum values defined in
 * `apps/api/src/db/schema/enums.ts`.
 *
 * | Value       | Meaning                                      |
 * |-------------|----------------------------------------------|
 * | `active`    | Currently actionable opportunity              |
 * | `closed`    | Position closed (hit target or stop loss)     |
 * | `expired`   | Opportunity window has passed                 |
 * | `cancelled` | Manually cancelled or invalidated             |
 */
export enum OpportunityStatus {
  ACTIVE = 'active',
  CLOSED = 'closed',
  EXPIRED = 'expired',
  CANCELLED = 'cancelled',
}

// ---------------------------------------------------------------------------
// TradeOpportunity Interface
// ---------------------------------------------------------------------------

/**
 * Represents a single trade recommendation generated by the LangGraph
 * analysis pipeline's recommendation node (Claude Sonnet 4.6).
 *
 * Maps directly to the `trade_opportunities` database table. All price fields
 * are `string` to preserve PostgreSQL `numeric(12,4)` precision — NEVER use
 * JavaScript `number` for financial values (AAP Rule 0.7.2).
 *
 * Key invariants:
 * - `articleId` references the originating `news_articles.id` row
 * - `entryPrice`, `stopLoss`, `takeProfit` are validated against actual market
 *   data from APIs to prevent LLM hallucinations (AAP Rule 0.7.2)
 * - `confidence` is in range 0.00–1.00, stored as `numeric(3,2)`
 * - `riskRewardRatio` is computed: (takeProfit - entryPrice) / (entryPrice - stopLoss)
 */
export interface TradeOpportunity {
  /** UUID v4 primary key. */
  id: string;

  /** Foreign key referencing the originating news article. */
  articleId: string;

  /**
   * Ticker symbol for the recommended instrument.
   * Examples: `'AAPL'`, `'RELIANCE'`, `'BTC'`, `'ETH'`.
   */
  symbol: string;

  /** Market category this opportunity belongs to. */
  market: Market;

  /** Recommended trade direction (LONG = buy, SHORT = sell). */
  direction: Direction;

  /**
   * Recommended entry price as a string (PostgreSQL `numeric(12,4)`).
   * Validated against actual market data to prevent LLM hallucinations.
   */
  entryPrice: string;

  /**
   * Stop loss price as a string (PostgreSQL `numeric(12,4)`).
   * The price at which the position should be closed to limit losses.
   */
  stopLoss: string;

  /**
   * Take profit price as a string (PostgreSQL `numeric(12,4)`).
   * The price at which the position should be closed to realize gains.
   */
  takeProfit: string;

  /**
   * Pipeline confidence score in range 0.00–1.00.
   * Stored as PostgreSQL `numeric(3,2)`.
   */
  confidence: number;

  /** Recommended trade timeframe. */
  timeframe: Timeframe;

  /**
   * Computed risk/reward ratio: (takeProfit - entry) / (entry - stopLoss).
   * Stored as a string (PostgreSQL `numeric(8,2)`).
   */
  riskRewardRatio: string;

  /**
   * LLM-generated reasoning for this trade recommendation.
   * Produced by the recommendation node (Claude Sonnet 4.6) using
   * DK-CoT (Domain Knowledge Chain-of-Thought) prompting.
   */
  reasoning: string;

  /** Current lifecycle status of this opportunity. */
  status: OpportunityStatus;

  /** ISO 8601 timestamp of when the opportunity was created. */
  createdAt: string;

  /** ISO 8601 timestamp of the last update. */
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// TradePerformance Interface
// ---------------------------------------------------------------------------

/**
 * Tracks the actual performance outcome of a trade opportunity.
 *
 * Maps directly to the `trade_performance` database table. Created when
 * an opportunity's status transitions to `closed`, recording the actual
 * exit price and computed profit/loss.
 *
 * Key invariants:
 * - `opportunityId` is a one-to-one relationship with `trade_opportunities.id`
 * - All monetary values are `string` (PostgreSQL `numeric(12,4)`)
 * - `pnlPercentage` is `string` (PostgreSQL `numeric(8,4)`)
 * - `isWin` is computed: true if P&L > 0, false otherwise
 */
export interface TradePerformance {
  /** UUID v4 primary key. */
  id: string;

  /** Foreign key referencing the associated trade opportunity (one-to-one). */
  opportunityId: string;

  /**
   * Actual exit / close price as a string (PostgreSQL `numeric(12,4)`).
   */
  actualExitPrice: string;

  /**
   * Absolute profit or loss amount as a string (PostgreSQL `numeric(12,4)`).
   * Negative values indicate a loss.
   */
  pnlAmount: string;

  /**
   * Percentage profit or loss as a string (PostgreSQL `numeric(8,4)`).
   * Negative values indicate a loss.
   */
  pnlPercentage: string;

  /** Whether the trade was profitable (`pnlAmount > 0`). */
  isWin: boolean;

  /** ISO 8601 timestamp of when the position was closed. */
  closedAt: string;

  /** ISO 8601 timestamp of when the performance record was created. */
  createdAt: string;
}
