/**
 * Trade Opportunity and Performance Domain Type Definitions
 *
 * Types for the Trading Intelligence Application's trade analysis and
 * recommendation system. These types map directly to the `trade_opportunities`
 * and `trade_performance` database tables and are consumed by:
 *   - `apps/api/src/services/analyzer/` — LangGraph pipeline output
 *   - `apps/api/src/services/notifier/`  — Telegram alert formatting
 *   - `apps/api/src/routes/opportunities.routes.ts` — REST API responses
 *   - `apps/api/src/routes/performance.routes.ts`   — Performance tracking API
 *   - `apps/web/src/pages/TradeOpportunities.tsx`    — Dashboard display
 *   - `apps/web/src/pages/Performance.tsx`           — Performance charts
 *
 * Design constraints (AAP Rules):
 * - No `any` type — specific types for every field (Rule 0.7.1)
 * - String enums with lowercase values matching PostgreSQL enum definitions
 *   in `apps/api/src/db/schema/enums.ts`
 * - All price fields are `string` — representing PostgreSQL `numeric(12,4)`,
 *   NEVER JavaScript floating-point `number` (Rule 0.7.2)
 * - Confidence uses `number` (range 0.00–1.00) — `numeric(3,2)` in database
 * - All date fields use ISO 8601 `string` for JSON serialization, not `Date`
 * - ESM imports use `.js` extension (Rule 0.7.1)
 * - Compiles under TypeScript strict mode with `exactOptionalPropertyTypes`
 *
 * @module @trading-intelligence/types/trade
 */

import { Market } from './news.js';

// ---------------------------------------------------------------------------
// Direction Enum
// ---------------------------------------------------------------------------

/**
 * Trade direction indicator for a recommended position.
 *
 * String values MUST match the PostgreSQL `direction` enum values defined in
 * `apps/api/src/db/schema/enums.ts`.
 *
 * Telegram alert emoji mapping (AAP Rule 0.7.5):
 * - `LONG`  → 🟢 (buy recommendation)
 * - `SHORT` → 🔴 (sell recommendation)
 */
export enum Direction {
  /** Buy recommendation — enter a long position. */
  LONG = 'long',
  /** Sell recommendation — enter a short position. */
  SHORT = 'short',
}

// ---------------------------------------------------------------------------
// Timeframe Enum
// ---------------------------------------------------------------------------

/**
 * Trade timeframe classification for how long a position is expected to be held.
 *
 * String values MUST match the PostgreSQL `timeframe` enum values defined in
 * `apps/api/src/db/schema/enums.ts`.
 *
 * | Value         | Holding Period              |
 * |---------------|-----------------------------|
 * | `INTRADAY`    | Same-day trades             |
 * | `SWING`       | Multi-day to multi-week     |
 * | `POSITION`    | Multi-week to multi-month   |
 */
export enum Timeframe {
  /** Same-day trades — positions opened and closed within a single trading session. */
  INTRADAY = 'intraday',
  /** Multi-day to multi-week trades — capitalizing on short-to-medium term trends. */
  SWING = 'swing',
  /** Multi-week to multi-month trades — based on longer-term fundamental catalysts. */
  POSITION = 'position',
}

// ---------------------------------------------------------------------------
// OpportunityStatus Enum
// ---------------------------------------------------------------------------

/**
 * Lifecycle status of a trade opportunity.
 *
 * String values MUST match the PostgreSQL `status` enum values defined in
 * `apps/api/src/db/schema/enums.ts`.
 *
 * | Value       | Meaning                                      |
 * |-------------|----------------------------------------------|
 * | `ACTIVE`    | Currently actionable opportunity              |
 * | `CLOSED`    | Position closed (hit target or stop loss)     |
 * | `EXPIRED`   | Opportunity window has passed                 |
 * | `CANCELLED` | Manually cancelled or invalidated             |
 */
export enum OpportunityStatus {
  /** Currently actionable — the opportunity is live and tradeable. */
  ACTIVE = 'active',
  /** Position closed — either the target was hit or the stop loss was triggered. */
  CLOSED = 'closed',
  /** Opportunity expired — the recommended timeframe has elapsed without entry. */
  EXPIRED = 'expired',
  /** Manually cancelled or invalidated by updated analysis. */
  CANCELLED = 'cancelled',
}

// ---------------------------------------------------------------------------
// TradeOpportunity Interface
// ---------------------------------------------------------------------------

/**
 * Represents a single trade recommendation generated by the LangGraph
 * analysis pipeline's recommendation node (Claude Sonnet 4.6).
 *
 * Maps directly to the `trade_opportunities` database table. All price fields
 * are `string` to preserve PostgreSQL `numeric(12,4)` precision — NEVER use
 * JavaScript `number` for financial values (AAP Rule 0.7.2).
 *
 * Key invariants:
 * - `articleId` references the originating `news_articles.id` row.
 * - `entryPrice`, `stopLoss`, `takeProfit` are validated against actual market
 *   data from APIs to prevent LLM hallucinations (AAP Rule 0.7.2). Any price
 *   more than 10% away from the current market price is flagged.
 * - `confidence` is in range 0.00–1.00, stored as `numeric(3,2)`.
 * - `riskRewardRatio` is computed: (takeProfit − entryPrice) / (entryPrice − stopLoss)
 *   for LONG trades, or the inverse for SHORT trades.
 */
export interface TradeOpportunity {
  /** UUID v4 primary key. */
  id: string;

  /** Foreign key referencing the originating news article (`news_articles.id`). */
  articleId: string;

  /**
   * Ticker symbol for the recommended instrument.
   * Examples: `'AAPL'`, `'RELIANCE'`, `'BTC'`, `'ETH'`.
   */
  symbol: string;

  /** Market category this opportunity belongs to. */
  market: Market;

  /** Recommended trade direction (LONG = buy, SHORT = sell). */
  direction: Direction;

  /**
   * Pipeline confidence score in range 0.00–1.00.
   * Stored as PostgreSQL `numeric(3,2)`. This is a score, NOT a financial
   * price, so `number` is appropriate here.
   */
  confidence: number;

  /**
   * Recommended entry price as a string (PostgreSQL `numeric(12,4)`).
   * Validated against actual market data to prevent LLM hallucinations.
   * CRITICAL: `string` type, NOT `number` — per AAP Rule 0.7.2.
   */
  entryPrice: string;

  /**
   * Stop loss price as a string (PostgreSQL `numeric(12,4)`).
   * The price at which the position should be closed to limit losses.
   * CRITICAL: `string` type, NOT `number` — per AAP Rule 0.7.2.
   */
  stopLoss: string;

  /**
   * Take profit price as a string (PostgreSQL `numeric(12,4)`).
   * The price at which the position should be closed to realize gains.
   * CRITICAL: `string` type, NOT `number` — per AAP Rule 0.7.2.
   */
  takeProfit: string;

  /** Recommended trade timeframe (INTRADAY, SWING, or POSITION). */
  timeframe: Timeframe;

  /**
   * LLM-generated reasoning for this trade recommendation.
   * Produced by the recommendation node (Claude Sonnet 4.6) using
   * DK-CoT (Domain Knowledge Chain-of-Thought) prompting.
   */
  reasoning: string;

  /**
   * Computed risk/reward ratio: (takeProfit − entry) / (entry − stopLoss).
   * Stored as a string to preserve decimal precision.
   * CRITICAL: `string` type, NOT `number` — per AAP Rule 0.7.2.
   */
  riskRewardRatio: string;

  /** Current lifecycle status of this opportunity. */
  status: OpportunityStatus;

  /** ISO 8601 timestamp of when the opportunity was created. */
  createdAt: string;

  /** ISO 8601 timestamp of the last update. */
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// TradePerformance Interface
// ---------------------------------------------------------------------------

/**
 * Tracks the actual performance outcome of a trade opportunity.
 *
 * Maps directly to the `trade_performance` database table. Created when
 * an opportunity's status transitions to `CLOSED`, recording the actual
 * entry/exit prices and computed profit/loss.
 *
 * Key invariants:
 * - `opportunityId` is a one-to-one relationship with `trade_opportunities.id`.
 * - All monetary and percentage values are `string` (PostgreSQL `numeric(12,4)`)
 *   to preserve financial decimal precision (AAP Rule 0.7.2).
 * - `isWin` is computed: `true` if P&L > 0, `false` otherwise.
 * - `exitReason` describes why the position was closed (e.g., stop hit, target
 *   reached, manual exit, time expiry).
 */
export interface TradePerformance {
  /** UUID v4 primary key. */
  id: string;

  /** Foreign key referencing the associated trade opportunity (one-to-one). */
  opportunityId: string;

  /**
   * Actual entry price as a string (PostgreSQL `numeric(12,4)`).
   * CRITICAL: `string` type, NOT `number` — per AAP Rule 0.7.2.
   */
  actualEntryPrice: string;

  /**
   * Actual exit / close price as a string (PostgreSQL `numeric(12,4)`).
   * CRITICAL: `string` type, NOT `number` — per AAP Rule 0.7.2.
   */
  actualExitPrice: string;

  /**
   * Percentage profit or loss as a string (PostgreSQL `numeric(12,4)`).
   * Negative values indicate a loss.
   * CRITICAL: `string` type, NOT `number` — per AAP Rule 0.7.2.
   */
  pnlPercent: string;

  /**
   * Absolute profit or loss amount as a string (PostgreSQL `numeric(12,4)`).
   * Negative values indicate a loss.
   * CRITICAL: `string` type, NOT `number` — per AAP Rule 0.7.2.
   */
  pnlAmount: string;

  /** Whether the trade was profitable (`pnlAmount > 0`). */
  isWin: boolean;

  /**
   * Reason why the position was closed.
   * Examples: `'stop_hit'`, `'target_reached'`, `'manual'`, `'expired'`.
   */
  exitReason: string;

  /** ISO 8601 timestamp of when the position was actually entered. */
  enteredAt: string;

  /** ISO 8601 timestamp of when the position was actually exited. */
  exitedAt: string;

  /** ISO 8601 timestamp of when the performance record was created. */
  createdAt: string;

  /** ISO 8601 timestamp of the last update to the performance record. */
  updatedAt: string;
}
