/**
 * Trade Opportunities Page — `apps/web/src/pages/TradeOpportunities.tsx`
 *
 * Route-level page component rendered at `/opportunities` inside
 * DashboardLayout. Displays a filterable, sortable, paginated board of
 * trade recommendations generated by the LangGraph analysis pipeline.
 *
 * Key features:
 * - **FilterBar integration** — Market, sort column, sort order, and
 *   search controls via the reusable FilterBar component
 * - **Extended filters** — Direction (LONG/SHORT), status (Active/Closed/
 *   Expired/Cancelled), timeframe, and minimum confidence threshold
 * - **TradeCard grid** — Each opportunity rendered as a TradeCard with
 *   direction emoji (🟢/🔴), price grid, confidence score, and reasoning
 * - **Pagination** — Page navigation with previous/next buttons and
 *   page counter
 * - **Polling-based refresh** — Auto-refreshes every 30 seconds per
 *   AAP §0.6.2 (no WebSocket — polling only)
 *
 * Architecture:
 * - Composes `useOpportunities` hook for paginated + filtered data fetching
 * - Composes `FilterBar` for market, sort, and search controls
 * - Dark theme CSS custom properties from globals.css
 * - All price fields displayed as raw strings — NO parseFloat or Number()
 *   (AAP Rule 0.7.2)
 * - TypeScript strict mode: no `any`, `exactOptionalPropertyTypes` enabled
 *
 * Per AAP §0.5.3:
 * - "Trade opportunities board with filters"
 * - "Filterable card grid displaying active opportunities with direction
 *    (LONG/SHORT), confidence score, entry/stop/target prices, and
 *    risk-reward ratio"
 *
 * @module apps/web/src/pages/TradeOpportunities
 */

import { useCallback, type ChangeEvent } from 'react';
import clsx from 'clsx';

import { useOpportunities } from '../hooks/useOpportunities';
import FilterBar from '../components/FilterBar';
import TradeCard from '../components/TradeCard';
import {
  Direction,
  OpportunityStatus,
  Timeframe,
  type Market,
} from '../types';

// ---------------------------------------------------------------------------
// Constants — Filter Options
// ---------------------------------------------------------------------------

/**
 * Direction filter dropdown options.
 * `null` value represents "All Directions" (no filter applied).
 */
const DIRECTION_OPTIONS: Array<{ value: Direction | null; label: string }> = [
  { value: null, label: 'All Directions' },
  { value: Direction.LONG, label: '🟢 Long' },
  { value: Direction.SHORT, label: '🔴 Short' },
];

/**
 * Opportunity status filter dropdown options.
 * `null` value represents "All Statuses" (no filter applied).
 */
const STATUS_OPTIONS: Array<{ value: OpportunityStatus | null; label: string }> = [
  { value: null, label: 'All Statuses' },
  { value: OpportunityStatus.ACTIVE, label: 'Active' },
  { value: OpportunityStatus.CLOSED, label: 'Closed' },
  { value: OpportunityStatus.EXPIRED, label: 'Expired' },
  { value: OpportunityStatus.CANCELLED, label: 'Cancelled' },
];

/**
 * Timeframe filter dropdown options.
 * `null` value represents "All Timeframes" (no filter applied).
 */
const TIMEFRAME_OPTIONS: Array<{ value: Timeframe | null; label: string }> = [
  { value: null, label: 'All Timeframes' },
  { value: Timeframe.INTRADAY, label: 'Intraday' },
  { value: Timeframe.SWING, label: 'Swing' },
  { value: Timeframe.POSITION, label: 'Positional' },
];

/**
 * Sort column options for the FilterBar's sort-by dropdown.
 */
const SORT_OPTIONS = [
  { value: 'createdAt', label: 'Date Created' },
  { value: 'confidence', label: 'Confidence' },
  { value: 'symbol', label: 'Symbol' },
  { value: 'market', label: 'Market' },
];

// ---------------------------------------------------------------------------
// TradeOpportunities Page Component
// ---------------------------------------------------------------------------

/**
 * Trade opportunities board page with FilterBar, extended filters,
 * TradeCard grid, and pagination controls.
 *
 * State management is fully delegated to the `useOpportunities` hook,
 * which provides individual setter functions for each filter dimension
 * and pagination. This component orchestrates the UI and delegates
 * state changes to the hook.
 */
export default function TradeOpportunities() {
  // -----------------------------------------------------------------------
  // Data hook — filtered, sorted, paginated trade opportunities
  // -----------------------------------------------------------------------

  const {
    opportunities,
    pagination,
    loading,
    error,
    refetch,
    filters,
    setPage,
    setMarket,
    setStatus,
    setDirection,
    setMinConfidence,
    setTimeframe,
    setSortBy,
    setSortOrder,
  } = useOpportunities({ pollingInterval: 30_000 });

  // -----------------------------------------------------------------------
  // Handlers — Extended filter changes
  // -----------------------------------------------------------------------

  /**
   * Handle direction filter dropdown changes.
   * Converts the string value back to a Direction enum or null.
   */
  const handleDirectionChange = useCallback(
    (e: ChangeEvent<HTMLSelectElement>): void => {
      const val = e.target.value;
      setDirection(val === '' ? null : (val as Direction));
    },
    [setDirection],
  );

  /**
   * Handle status filter dropdown changes.
   * Converts the string value back to an OpportunityStatus enum or null.
   */
  const handleStatusChange = useCallback(
    (e: ChangeEvent<HTMLSelectElement>): void => {
      const val = e.target.value;
      setStatus(val === '' ? null : (val as OpportunityStatus));
    },
    [setStatus],
  );

  /**
   * Handle timeframe filter dropdown changes.
   * Converts the string value back to a Timeframe enum or null.
   */
  const handleTimeframeChange = useCallback(
    (e: ChangeEvent<HTMLSelectElement>): void => {
      const val = e.target.value;
      setTimeframe(val === '' ? null : (val as Timeframe));
    },
    [setTimeframe],
  );

  /**
   * Handle confidence threshold slider changes.
   * Converts the 0-100 integer range to 0.00-1.00 decimal, or null if 0.
   */
  const handleConfidenceChange = useCallback(
    (e: ChangeEvent<HTMLInputElement>): void => {
      const value = parseInt(e.target.value, 10);
      setMinConfidence(value === 0 ? null : value / 100);
    },
    [setMinConfidence],
  );

  /**
   * Handle market filter changes from the FilterBar component.
   */
  const handleMarketChange = useCallback(
    (market: Market | null): void => {
      setMarket(market);
    },
    [setMarket],
  );

  // -----------------------------------------------------------------------
  // Pagination handlers
  // -----------------------------------------------------------------------

  const handlePrevPage = useCallback((): void => {
    if (pagination && pagination.page > 1) {
      setPage(pagination.page - 1);
    }
  }, [pagination, setPage]);

  const handleNextPage = useCallback((): void => {
    if (pagination && pagination.page < pagination.totalPages) {
      setPage(pagination.page + 1);
    }
  }, [pagination, setPage]);

  // -----------------------------------------------------------------------
  // Derived state
  // -----------------------------------------------------------------------

  const confidenceDisplay = filters.minConfidence !== null
    ? Math.round(filters.minConfidence * 100)
    : 0;

  // -----------------------------------------------------------------------
  // Render
  // -----------------------------------------------------------------------

  return (
    <div className="page-content">
      {/* Page header */}
      <div className="page-header">
        <h1 className="page-title">📊 Trade Opportunities</h1>
        <p className="text-secondary text-sm">
          AI-generated trade recommendations from the analysis pipeline
        </p>
      </div>

      {/* FilterBar — market, sort column, sort order, search */}
      <FilterBar
        market={filters.market}
        onMarketChange={handleMarketChange}
        sortBy={filters.sortBy}
        onSortByChange={setSortBy}
        sortOrder={filters.sortOrder}
        onSortOrderChange={setSortOrder}
        search=""
        onSearchChange={() => {
          /* Search not implemented for opportunities endpoint */
        }}
        sortOptions={SORT_OPTIONS}
      >
        {/* Extended filters rendered inside FilterBar's children slot */}
        <div className="flex items-center gap-2 flex-wrap">
          {/* Direction filter */}
          <select
            value={filters.direction ?? ''}
            onChange={handleDirectionChange}
            className="filter-select"
            aria-label="Filter by direction"
          >
            {DIRECTION_OPTIONS.map((opt) => (
              <option key={opt.label} value={opt.value ?? ''}>
                {opt.label}
              </option>
            ))}
          </select>

          {/* Status filter */}
          <select
            value={filters.status ?? ''}
            onChange={handleStatusChange}
            className="filter-select"
            aria-label="Filter by status"
          >
            {STATUS_OPTIONS.map((opt) => (
              <option key={opt.label} value={opt.value ?? ''}>
                {opt.label}
              </option>
            ))}
          </select>

          {/* Timeframe filter */}
          <select
            value={filters.timeframe ?? ''}
            onChange={handleTimeframeChange}
            className="filter-select"
            aria-label="Filter by timeframe"
          >
            {TIMEFRAME_OPTIONS.map((opt) => (
              <option key={opt.label} value={opt.value ?? ''}>
                {opt.label}
              </option>
            ))}
          </select>

          {/* Confidence threshold slider */}
          <div className="flex items-center gap-2">
            <label
              htmlFor="confidence-filter"
              className="text-secondary text-sm whitespace-nowrap"
            >
              Min Confidence:
            </label>
            <input
              id="confidence-filter"
              type="range"
              min="0"
              max="100"
              step="5"
              value={confidenceDisplay}
              onChange={handleConfidenceChange}
              className="confidence-slider"
              aria-label="Minimum confidence threshold"
              aria-valuemin={0}
              aria-valuemax={100}
              aria-valuenow={confidenceDisplay}
              aria-valuetext={`${String(confidenceDisplay)} percent`}
            />
            <span className="text-sm font-mono whitespace-nowrap">
              {confidenceDisplay}%
            </span>
          </div>
        </div>
      </FilterBar>

      {/* Error state */}
      {error !== null && (
        <div className="card text-center py-8" role="alert">
          <p className="text-danger mb-3">{error}</p>
          <button
            type="button"
            className="btn btn-primary"
            onClick={refetch}
          >
            Retry
          </button>
        </div>
      )}

      {/* Loading state */}
      {loading && opportunities.length === 0 && error === null && (
        <div className="card text-center py-8" role="status">
          <p className="text-secondary">Loading trade opportunities...</p>
        </div>
      )}

      {/* Empty state */}
      {!loading && opportunities.length === 0 && error === null && (
        <div className="card text-center py-8">
          <p className="text-secondary text-lg mb-2">
            No trade opportunities found
          </p>
          <p className="text-tertiary text-sm">
            Adjust your filters or wait for the analysis pipeline to generate
            new recommendations.
          </p>
        </div>
      )}

      {/* Trade opportunity card grid */}
      {opportunities.length > 0 && (
        <div className="card-grid">
          {opportunities.map((opportunity) => (
            <TradeCard
              key={opportunity.id}
              opportunity={opportunity}
            />
          ))}
        </div>
      )}

      {/* Pagination controls */}
      {pagination !== null && pagination.totalPages > 1 && (
        <nav
          className="flex items-center justify-center gap-4 py-4"
          aria-label="Pagination"
        >
          <button
            type="button"
            className={clsx(
              'btn btn-secondary',
              pagination.page <= 1 && 'btn-disabled',
            )}
            onClick={handlePrevPage}
            disabled={pagination.page <= 1}
            aria-label="Previous page"
          >
            ← Previous
          </button>

          <span className="text-secondary text-sm">
            Page {String(pagination.page)} of {String(pagination.totalPages)}
            {' '}({String(pagination.total)} total)
          </span>

          <button
            type="button"
            className={clsx(
              'btn btn-secondary',
              pagination.page >= pagination.totalPages && 'btn-disabled',
            )}
            onClick={handleNextPage}
            disabled={pagination.page >= pagination.totalPages}
            aria-label="Next page"
          >
            Next →
          </button>
        </nav>
      )}
    </div>
  );
}
